version: '2'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    #image: pyar/pyarweb:dev
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_CONFIGURATION=Prod
      - DJANGO_SETTINGS_MODULE=website.settings
    command: gunicorn website.wsgi -b 0.0.0.0:8000

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes_from:
      - web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
