version: '2'

volumes:
  pgdata:

services:
  postgres:
      restart: always
      image: postgres:9.4.4  # Lets update later...
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
      environment:
        - POSTGRES_PASSWORD=secret

  web:
      #image: pyar/pyarweb:dev
      build: .
      command: python3 website/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      links:
        - postgres
      depends_on:
        - postgres
      environment:
        - DB_USER=postgres
        - DB_NAME=postgres
        - DB_PASS=secret
        - DB_SERVICE=postgres
